### ISSUE TITLE
Unable to get to traefik ingress

### ISSUE THREAD

**Issue by META-DREAMER** [k8s-at-home/template-cluster-k3s#206] opened 2022-02-02 22:34 UTC
# Details

Whenever I try to connect to the ingress IP I get a 522 error. Looking at the traefik helm-release, shouldnt there be 443 and 80 ports open here? Still learning this stuff...

```yml
    ports:
      traefik:
        expose: true
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
```

**What did you expect to happen:**

I am able to access the hajimari dashboard

**Anything else you would like to add:**

**Additional Information:**

**Comment by onedr0p** [comment] 2022-02-03 00:38
80 and 443 are exposed on the loadBalancerIP. It's already defined in the default values, so no need to redefine them.

https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L299

**Comment by META-DREAMER** [comment] 2022-02-03 00:46
Do you know what else could be causing this issue then? I'm not able to load hajimari or traefik dashboard or anything. DNS records are setup correctly in cloudflare and the ports are open on my router forwarding to the `BOOTSTRAP_METALLB_TRAEFIK_ADDR`. Even when I try to set the DNS in my pihole locally to point to that IP address or in my hosts file, it still doesnt give me access to the dashboard.

**Comment by onedr0p** [comment] 2022-02-03 00:50
522 seems like a cert issue, are you sure cert-manager was able to successfully create your certs?

**Comment by onedr0p** [comment] 2022-02-03 00:53
Also, are you even able to curl your traefik load balancer IP locally?

```
curl -vvv -L -k https://IP:443
```

**Comment by META-DREAMER** [comment] 2022-02-03 01:30
How can I verify if it was able to create the certs? 

This is what I get when trying to curl the `BOOTSTRAP_METALLB_TRAEFIK_ADDR `:

```
*   Trying 192.168.20.210:443...
* Connected to 192.168.20.210 (192.168.20.210) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* LibreSSL SSL_connect: Broken pipe in connection to 192.168.20.210:443
* Closing connection 0
curl: (35) LibreSSL SSL_connect: Broken pipe in connection to 192.168.20.210:443
```

**Comment by onedr0p** [comment] 2022-02-03 01:57
```
kubectl get certificates -A
```

Are the certs showing as ready?

**Comment by META-DREAMER** [comment] 2022-02-03 05:01
Yes they show Ready there

**Comment by onedr0p** [comment] 2022-02-03 09:37
That curl statement above should return a 404... You have something messed up internally and that's why it's not working thru cloudflare.

**Comment by META-DREAMER** [comment] 2022-02-03 21:58
```
NAMESPACE                   NAME                                              READY   STATUS      RESTARTS      AGE
calico-system               calico-kube-controllers-7cd6f7b9f9-h9xzd          1/1     Running     0             39h
calico-system               calico-node-49zcx                                 1/1     Running     0             39h
calico-system               calico-node-9gjzm                                 1/1     Running     0             39h
calico-system               calico-node-jkdm7                                 1/1     Running     0             39h
calico-system               calico-node-k5rrn                                 1/1     Running     0             39h
calico-system               calico-node-nw65n                                 1/1     Running     0             39h
calico-system               calico-node-qrxk6                                 1/1     Running     0             39h
calico-system               calico-typha-ffbb657cb-9bwp2                      1/1     Running     0             39h
calico-system               calico-typha-ffbb657cb-llck6                      1/1     Running     0             39h
calico-system               calico-typha-ffbb657cb-zztzr                      1/1     Running     0             39h
cattle-fleet-local-system   fleet-agent-78f694664b-2dvsc                      1/1     Running     0             24h
cattle-fleet-system         fleet-controller-6666887949-6kx9p                 1/1     Running     0             24h
cattle-fleet-system         gitjob-7b97c9c7fd-csrq2                           1/1     Running     0             24h
cert-manager                cert-manager-75bcb7bd5-qz2jb                      1/1     Running     0             39h
cert-manager                cert-manager-cainjector-5c747645bf-9vcjf          1/1     Running     0             39h
cert-manager                cert-manager-webhook-f588b48b8-8ccmn              1/1     Running     0             39h
default                     cm-acme-http-solver-crh6l                         1/1     Running     0             48m
default                     hajimari-7758697c64-6trsb                         1/1     Running     0             39h
flux-system                 helm-controller-544df4db67-f6r9b                  1/1     Running     0             39h
flux-system                 kustomize-controller-5f964db78c-74vb5             1/1     Running     0             39h
flux-system                 notification-controller-b55cbcf9c-jrnjg           1/1     Running     0             39h
flux-system                 source-controller-84897ffd55-x7wzv                1/1     Running     0             39h
kube-system                 coredns-96cc4f57d-6hjnt                           1/1     Running     0             39h
kube-system                 kube-vip-24xxw                                    1/1     Running     2 (24h ago)   39h
kube-system                 kube-vip-9n77b                                    1/1     Running     0             39h
kube-system                 kube-vip-xbvw8                                    1/1     Running     3 (24h ago)   39h
kube-system                 local-path-provisioner-84bb864455-zggrh           1/1     Running     0             39h
kube-system                 metrics-server-75ff75cf87-96g4f                   1/1     Running     0             39h
kube-system                 node-shell-5c41f479-d458-4a0e-b9d0-a511d219e6db   1/1     Running     0             49m
kube-system                 node-shell-9686d0d7-95f8-4150-8d78-869c596c9032   0/1     Completed   0             16h
kube-system                 reflector-5549cd8bfd-k89g9                        1/1     Running     0             39h
kube-system                 reloader-5575bbf677-92x6k                         1/1     Running     0             39h
metallb-system              metallb-controller-7cb7dd579d-p8fwx               1/1     Running     0             39h
metallb-system              metallb-speaker-66lj4                             1/1     Running     0             39h
metallb-system              metallb-speaker-dhqqh                             1/1     Running     0             39h
metallb-system              metallb-speaker-fxghw                             1/1     Running     0             39h
metallb-system              metallb-speaker-k4jh4                             1/1     Running     0             39h
metallb-system              metallb-speaker-kkznf                             1/1     Running     0             39h
metallb-system              metallb-speaker-n26hx                             1/1     Running     0             39h
networking                  traefik-5b94d94d74-tjdsq                          1/1     Running     0             22h
system-upgrade              system-upgrade-controller-c48cb89f9-pcwsx         1/1     Running     0             39h
tigera-operator             tigera-operator-c4b9549c7-646sw                   1/1     Running     1 (39h ago)   39h
NAMESPACE                   NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
calico-system               calico-kube-controllers     1/1     1            1           39h
calico-system               calico-typha                3/3     3            3           39h
cattle-fleet-local-system   fleet-agent                 1/1     1            1           24h
cattle-fleet-system         fleet-controller            1/1     1            1           24h
cattle-fleet-system         gitjob                      1/1     1            1           24h
cert-manager                cert-manager                1/1     1            1           39h
cert-manager                cert-manager-cainjector     1/1     1            1           39h
cert-manager                cert-manager-webhook        1/1     1            1           39h
default                     hajimari                    1/1     1            1           39h
flux-system                 helm-controller             1/1     1            1           39h
flux-system                 kustomize-controller        1/1     1            1           39h
flux-system                 notification-controller     1/1     1            1           39h
flux-system                 source-controller           1/1     1            1           39h
kube-system                 coredns                     1/1     1            1           39h
kube-system                 local-path-provisioner      1/1     1            1           39h
kube-system                 metrics-server              1/1     1            1           39h
kube-system                 reflector                   1/1     1            1           39h
kube-system                 reloader                    1/1     1            1           39h
metallb-system              metallb-controller          1/1     1            1           39h
networking                  traefik                     1/1     1            1           39h
system-upgrade              system-upgrade-controller   1/1     1            1           39h
tigera-operator             tigera-operator             1/1     1            1           39h
NAMESPACE        NAME             READY   STATUS                             AGE
cert-manager     cert-manager     True    Release reconciliation succeeded   39h
default          hajimari         True    Release reconciliation succeeded   39h
kube-system      metrics-server   True    Release reconciliation succeeded   39h
kube-system      reflector        True    Release reconciliation succeeded   39h
kube-system      reloader         True    Release reconciliation succeeded   39h
metallb-system   metallb          True    Release reconciliation succeeded   39h
networking       traefik          True    Release reconciliation succeeded   39h
NAMESPACE     NAME           READY   STATUS                                                                AGE
flux-system   apps           True    Applied revision: main/7fc492b0bd9e61bc7bf504c8ed68570e8cb25ba6       39h
flux-system   core           True    Applied revision: main/7fc492b0bd9e61bc7bf504c8ed68570e8cb25ba6       39h
flux-system   crds           True    Applied revision: main/7fc492b0bd9e61bc7bf504c8ed68570e8cb25ba6       39h
flux-system   flux-system    True    Applied revision: main/7fc492b0bd9e61bc7bf504c8ed68570e8cb25ba6       39h
flux-system   traefik-crds   True    Applied revision: v10.13.0/6aae2789613d5cde6767dd1f809ca05f667f3959   39h
NAMESPACE    NAME                    READY   SECRET                  AGE
default      hajimari-tls            True    hajimari-tls            39h
default      tls-rancher-ingress     False   tls-rancher-ingress     50m
networking   traefik-dashboard-tls   True    traefik-dashboard-tls   39h
```

**Comment by onedr0p** [comment] 2022-02-03 23:05
It really looks like something outside your cluster is interfering with the networking...

**Comment by onedr0p** [comment] 2022-02-04 01:10
I'm also curious why you are installing rancher/fleet? It looks like you are trying to use 2 different GitOps tools in your cluster, that might cause issues down the road.

**Comment by META-DREAMER** [comment] 2022-02-04 06:47
Ok, thanks for all your help debugging. Will investigate further as to what's going on. I turned off almost all the firewall rules in my router to ensure that wasn't getting in the way, so likely something up with MetalLB. Any idea how I could debug that?

Was just testing out Rancher. I think it comes with Fleet by default now. Was thinking of potentially replacing Flux for Fleet.

**Comment by onedr0p** [comment] 2022-02-04 13:27
It looks like you can connect to the LB IP `Connected to 192.168.20.210 (192.168.20.210) port 443 (#0)` but this looks very odd...

```
* LibreSSL SSL_connect: Broken pipe in connection to 192.168.20.210:443
* Closing connection 0
curl: (35) LibreSSL SSL_connect: Broken pipe in connection to 192.168.20.210:443
```

I have not seen that error before.

**Comment by META-DREAMER** [comment] 2022-02-04 19:01
Just tried it again, getting this error now:
```
*   Trying 192.168.20.210:443...
* Connected to 192.168.20.210 (192.168.20.210) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS alert, internal error (592):
* error:14004438:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert internal error
* Closing connection 0
curl: (35) error:14004438:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert internal error
```

**Comment by onedr0p** [comment] 2022-02-04 23:50
Can you look at the traefik logs while you run that curl command and see if it shows anything?

**Comment by META-DREAMER** [comment] 2022-02-05 03:13
Yea, traefik shows this:
```
{"level":"debug","msg":"http: TLS handshake error from 192.168.20.198:52588: strict SNI enabled - No certificate found for domain: \"\", closing connection","time":"2022-02-05T03:12:43Z"}
```

**Comment by onedr0p** [comment] 2022-02-05 04:18
I think that makes sense, what about when you try to run 

`dig hajimari.<yourdomain>`

`dig @<pihole-ip> hajimari.<yourdomain>`

`curl -vvv -L -k https://hajimari.<yourdomain>`

**Comment by META-DREAMER** [comment] 2022-02-05 07:05
`dig hajimari.<yourdomain>`:

```
; <<>> DiG 9.10.6 <<>> hajimari.<mydomain>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57065
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;hajimari.<mydomain>.		IN	A

;; ANSWER SECTION:
hajimari.<mydomain>.	300	IN	A	104.21.x.x  (cloudflare ip hidden)
hajimari.<mydomain>.	300	IN	A	172.67.133.165 (cloudflare ip hidden)

;; Query time: 17 msec
;; SERVER: 192.168.0.10#53(192.168.0.10)
;; WHEN: Fri Feb 04 23:58:06 MST 2022
;; MSG SIZE  rcvd: 76
```

`dig @<pihole-ip> hajimari.<yourdomain>`:
```
; <<>> DiG 9.10.6 <<>> @192.168.0.10 hajimari.<mydomain>
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43969
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;hajimari.<mydomain>.		IN	A

;; ANSWER SECTION:
hajimari.<mydomain>.	264	IN	A	172.67.x.x (cloudflare ip hidden)
hajimari.<mydomain>.	264	IN	A	104.21.x.x (cloudflare ip hidden)

;; Query time: 3 msec
;; SERVER: 192.168.0.10#53(192.168.0.10)
;; WHEN: Fri Feb 04 23:58:42 MST 2022
;; MSG SIZE  rcvd: 76
```

`curl -vvv -L -k https://hajimari.<yourdomain>`:
```
*   Trying 104.21.x.x:443...
* Connected to hajimari.<mydomain> (104.21.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jan  3 00:00:00 2022 GMT
*  expire date: Jan  3 23:59:59 2023 GMT
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x120012400)
> GET / HTTP/2
> Host: hajimari.<mydomain>
> user-agent: curl/7.77.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
```

No errors in Traefik

**Comment by onedr0p** [comment] 2022-02-05 13:25
> Even when I try to set the DNS in my pihole locally to point to that IP address or in my hosts file, it still doesn't give me access to the dashboard.

Why is DNS resolving to cloudflare? It should be resolving to `BOOTSTRAP_METALLB_TRAEFIK_ADDR`

**Comment by META-DREAMER** [comment] 2022-02-07 05:04
In main.tf isn't it setting up the ipv4 A record to point to my public IP? And then the hajimari record is just a CNAME for that ipv4 record, meaning that cloudflare proxy would be protecting my public IP from being visible.

I just tested it by adding my domain in pihole DNS to point to  `BOOTSTRAP_METALLB_TRAEFIK_ADDR` and adding a CNAME in pihole for hajimari to point to my domain, and with that it load`s properly locally, but still doesnt load when I remove the entries from pihole. I have port 80 and 443 forwarded to `BOOTSTRAP_METALLB_TRAEFIK_ADDR` in my router (UDM PRO)

**Comment by META-DREAMER** [comment] 2022-02-07 21:25
So looks like my ISP started blocking port 80/443 for "security" without telling me. Was working a couple months ago when I was last using them so didnt expect that to be the issue. No double NAT or CGNAT, UDM is working fine, its my ISP blocking it.

Would it be possible to use a port other than 80/443 externally via cloudflare and just route them to 80/443 on `BOOTSTRAP_METALLB_TRAEFIK_ADDR`? Thinking of doing that or setting up a [Tunnel](https://www.cloudflare.com/products/tunnel/)

Thanks for your patience and help with this, really appreciate it.

**Comment by onedr0p** [comment] 2022-02-07 22:58
Hey no problems! I am glad we actually have a root cause figured out.

As far as I am aware Cloudflare will only do HTTP/S traffic over port 80 and 443, if you need something outside of that you will want to look into solutions like [cloudflared](https://github.com/cloudflare/cloudflared) or perhaps [tailscale](https://tailscale.com/) to get around your 80/443 issue. I wish I had more guidance here, but there's many different ways it could be done.

`kub-vip` and `metallb` are used for different things here.`kube-vip` _can_ load balance Kubernetes services but for the purposes of this repo it is only used for the control plane nodes to balance the k8s API. `metallb` is only used to load balance k8s services.

**Closed** 2022-02-07 23:04 UTC

**Comment by minhtt159** [comment] 2022-06-12 01:58
@META-DREAMER Have you solved the problem? I'm deploying cloudflared now and got the same issue
