### ISSUE TITLE
bug: renovatebot flux update fails kubeval lint checks

### ISSUE THREAD

**Issue by ankushg** [k8s-at-home/template-cluster-k3s#217] opened 2022-02-08 21:18 UTC
Example: https://github.com/k8s-at-home/template-cluster-k3s/runs/5094865387?check_suite_focus=true

Would be nice if this didn't happen -- I personally like to block all PRs from being merged unless lint is passing

**Comment by onedr0p** [comment] 2022-02-08 22:54
I am not sure the best way to fix this since the `gotk-components.yaml` file is upstreamed from Flux, meaning anything you change in there will be overridden on Flux updates. It looks like the issue is with `kubeval`.

https://github.com/instrumenta/kubeval/issues/47

I also do not see where Flux publically puts their schemas for kubeval to use with the `--additional-schema-locations` flag, or even if that would fix the issue because kubeval is already using the `--ignore-missing-schemas` flag.

If you find out anything feel free to open a PR, or discuss further here. Thanks!

**Comment by onedr0p** [comment] 2022-04-16 04:43
Going to close this issue, if you find out a way to get around this please share!

**Closed by onedr0p** 2022-04-16 04:43 UTC
